@startuml
hide footbox
box List Resources for One Project
participant ":CommandHandler" as CH
participant ":ProjectManager" as PM
participant ":ResourceManager" as RM
participant ":Project" as P
participant ":Resource" as R


[-> CH: processCommand()
activate CH

CH -> CH: switchCommand()
activate CH

CH -> CH: listAProjectResource()
activate CH

CH -> PM: printResourceListForAProject()
activate PM

PM -> PM: userInputs = processInputs()
PM -> PM: userInputProjectName = validateAndExtractProjectNameInput()

loop for each project
    PM -> P: getProjectName()
    activate P
    return
    opt if projectName.equals(userInputProjectName)
        PM -> P: getResources()
        activate P
        return
        PM -> RM: printResourceList()
        activate RM
        loop for each resource
            RM -> R: print()
            activate R
            return
        end

        return
        return
        end
        end
        return
        return
return

@enduml