@startuml

box Adding Resource
participant ":CommandHandler" as CH
participant "<<class>>\n:CommandParser" as CP
participant ":Project" as P1
participant "projectInStorage:Project" as P2

[-> CH: processCommand()
activate CH

CH -> CH: processInputBeforeAdding()
activate CH

CH -> CP: decodeInfoFragments(infoFragments, keywords, firstOptionalKeyword)
activate CP
return projectInfo

CH -> CH: addResource(projectInfo)
activate CH

opt ProjectNotExist
    CH -> CH: createNewProject(projectName, projectUrl, descriptionOfUrl)
    activate CH
    create P1
    CH -> P1:
    return
end

alt UrlAlreadyExist
    CH -> CH: promptUserUrlAlreadyExist()
    activate CH
    return
else else
    CH -> CH: addNewResource(projectName, projectUrl, descriptionOfUrl, projectIndex)
    activate CH
    CH -> P2: addResources(projectUrl, descriptionOfUrl)
    activate P2
    return
    return
end

return
return
return isLoop

@enduml