@startuml

box Adding Project / Resource
participant ":CommandHandler" as CH
participant "<<class>>\n:CommandParser" as CP
participant "P1:Project" as P1
participant "P2:Project" as P2
participant "P3:Project" as P3
participant ":ArrayList<Project>" as PA

create PA
CH -> PA
[-> CH: processCommand()
activate CH

CH -> CH: processInputBeforeAdding()
activate CH

CH -> CP: decodeInfoFragments(infoFragments:String[], keywords:String[], firstOptionalKeyword:int)
activate CP
return projectInfo:String[]

CH -> CH: addResource(projectInfo:String[])
activate CH

CH -> CH: searchExistingProjectIndex(projectName:String)
activate CH
return projectIndex:int

opt ProjectNotExist
    CH -> CH: createNewProject(projectName:String, projectUrl:String, descriptionOfUrl:String)
    activate CH
    create P1
    CH -> P1: new Project(projectName:String, projectUrl:String, descriptionOfUrl:String)
    CH <-- P1: P1:Project
    CH -> PA: add(P1:Project)
    activate PA
    return
    return
end

alt UrlAlreadyExist
    CH -> CH: overwriteResource(projectName:String, projectUrl:String, descriptionOfUrl:String, projectIndex:int)
    activate CH
    CH -> PA: remove(projectIndex:int)
    activate PA
    return
    create P2
    CH -> P2: new Project(projectName:String, projectUrl:String, descriptionOfUrl:String)
    CH <-- P2: P2:Project
    CH -> PA: add(P2:Project)
    activate PA
    return
    return
else
    CH -> CH: addNewResource(projectName:String, projectUrl:String, descriptionOfUrl:String, projectIndex:int)
    activate CH
    CH -> PA: get(projectIndex:int)
    activate PA
    return P3:Project
    CH -> P3: addResources(projectUrl, descriptionOfUrl)
    activate P3
    return
    return
end

return
return
return isLoop:Boolean

@enduml