!define COLOR_COMMAND #33FFC4
!define COLOR_PARSER #7777DB
!define COLOR_PROJECT #5252CE
!define COLOR_RESOURCE #944444
!define COLOR_STORAGE #10EE10
!define COLOR_DUKE #11E9E8
!define COLOR_UI #FFFF99