@startuml
'https://plantuml.com/sequence-diagram

box Deleting Resource
participant ":Command Handler" as CommandHandler
participant ":Command Parser" as CommandParser
participant ":Resource Manager" as ResourceManager
participant ":Project Manager" as ProjectManager


[-> CommandHandler : processInputBeforeDeleting()
activate CommandHandler


CommandHandler -> CommandParser: decodeInfoFragment
activate CommandParser
CommandHandler <-- CommandParser : String[] projectInfo
deactivate CommandParser

CommandHandler -> ResourceManager : deleteResource(projectInfo)
activate ResourceManager
ResourceManager -> ProjectManager : getProjByProjName(projectName)
activate ProjectManager
ResourceManager <-- ProjectManager : targetedProj
deactivate ProjectManager

alt projectNotFound
    [<-- ResourceManager : ProjectNotFoundException
else invalidIndex
    [<-- ResourceManager : ResourceNotFoundException
else indexNotIndicated
    ResourceManager -> ProjectManager: deleteWholeProject(targetedProject)
    activate ProjectManager
    [<-- ProjectManager :
    deactivate ProjectManager

else else
    [<-- ResourceManager : targetedProj.getResources().remove(idx)
    deactivate
end


@enduml