@startuml

box list-all feature
participant ":CommandHandler" as CH
'participant "P1:Project" as P1
'participant "P2:Project" as P2
'participant "P3:Project" as P3
participant ":ArrayList<Project>" as PA
participant ":ArrayList<Resources>" as RA


create PA
CH -> PA

create RA
PA -> RA

[-> CH: processCommand()
activate CH

CH -> CH: printResourceListForAllProjects()
activate CH

loop Length of ArrayList<Project>
    CH -> PA
    activate PA
    PA -> RA: getResource()
    activate RA
    return
    return
    CH -> CH: printResourceList()
    activate CH
    loop Length of ArrayList<Resource>
        CH -> CH: print()
    end
end
endbox
return
return

return: IsLoop:boolean

@enduml