@startuml

box Exiting TraceYourProj
participant ":CommandHandler" as CH
participant ":MainUI" as MUI
end box


[-> CH : processCommand()]
activate CH

CH -> MUI : showExitMessage()
activate MUI
return

return isLoop



@enduml