@startuml
!include Style.puml

box Logic LOGIC_COLOR_T2
participant ":Duke" as Duke LOGIC_COLOR_T1
participant ":CommandHandler" as CommandHandler LOGIC_COLOR_T1
participant ":MainUI" as MainUI LOGIC_COLOR_T1
participant ":InputParser" as InputParser LOGIC_COLOR_T1
end box


box Model MODEL_COLOR_T1
participant ":Model" as MODEL_COLOR
end box

activate Duke
[-> Duke : execute("exit")]

create CommandHandler
Duke -> CommandHandler
Duke -> CommandHandler : processCommand()
activate CommandHandler

CommandHandler -> InputParser : getCommand()
activate InputParser

CommandHandler -> InputParser : getInfoFragments()
deactivate InputParser

CommandHandler -> MainUI : showExitMessage()
activate MainUI
deactivate MainUI

CommandHandler --> Duke : isLoop
deactivate CommandHandler

deactivate Duke
destroy Duke


@enduml