@startuml

box
participant ":CommandHandler" as CommandHandler
participant "Storage" as Storage
participant "ProjectManager" as ProjectManager
participant "Duke" as Duke
end box

activate CommandHandler
[-> CommandHandler : execute("load")]

CommandHandler -> Storage :  readFromStorage()
activate Storage

Storage --> CommandHandler : projects
deactivate Storage

CommandHandler -> ProjectManager : setProjects(projects)
activate ProjectManager

ProjectManager --> CommandHandler : "Projects loaded into TraceMyProj"


CommandHandler -> ProjectManager : getProjects()
activate Duke

ProjectManager --> CommandHandler : projects
deactivate ProjectManager

CommandHandler -> Duke : setProjects(projects)

deactivate CommandHandler
deactivate Duke

@enduml
